### ISSUE TITLE
你好 下载数据集相关问题

### ISSUE THREAD

**Issue by BeardedManZhao** [mc6666/DL_Book_SC#1]
* 问题描述
下载数据集的时候发生了问题，数据集链接失效了吗？
* 点击的链接：https://drive.google.com/file/d/1ysZGVFZT2v21lazVo5exxs1aHG89LQRq/view?usp=sharing
* 下面是引导我点击的链接页面
![image](https://github.com/mc6666/DL_Book_SC/assets/113756063/74a741e3-dead-4fa6-bdcb-d6af806e0d20)

**Comment by BeardedManZhao** [comment]
![image](https://github.com/mc6666/DL_Book_SC/assets/113756063/42106c40-fc4e-4e67-a4e3-6febc24dc108)

**Comment by mc6666** [comment]
我剛剛測試，是沒有問題的，是否被防火牆擋住了?
[image: image.png]




LingYuZhao ***@***.***> 於 2023年6月12日 週一 下午3:15寫道：

**Comment by BeardedManZhao** [comment]
好的，我了解了相关事项，感谢您的帮助，这边应该是网络问题。

**Comment by mc6666** [comment]
已上傳至百度，可自以下連結下載：
https://pan.baidu.com/s/1MqYgC3uesDXAHiKRWESRBQ?pwd=s7rh




LingYuZhao ***@***.***> 於 2023年6月13日 週二 上午11:20寫道：

**Comment by BeardedManZhao** [comment]
好的，感谢，这边已保存数据集。
